install:
  - C:\msys64\usr\bin\bash -lc 'pacman -Syu --noconfirm'
  - C:\msys64\usr\bin\bash -lc 'pacman -Syu --noconfirm'
  - C:\msys64\usr\bin\bash -lc 'pacman -S --noconfirm unzip'
  - C:\msys64\usr\bin\bash -lc 'pacman -S --noconfirm mingw-w64-x86_64-gst-python'
  - C:\msys64\usr\bin\bash -lc 'pacman -S --noconfirm mingw-w64-x86_64-gst-plugins-good mingw-w64-x86_64-gst-plugins-bad'
  - C:\msys64\usr\bin\bash -lc 'pacman -S --noconfirm mingw-w64-x86_64-python3-pip'
  - C:\msys64\usr\bin\bash -lc 'pacman -S --noconfirm mingw-w64-x86_64-python3-pyqt5'
  - C:\msys64\usr\bin\bash -lc 'pacman -S --noconfirm mingw-w64-x86_64-python3-numpy'
  - C:\msys64\usr\bin\bash -lc '/mingw64/bin/pip3.exe install pyqtgraph==0.11.0rc0'
  - C:\msys64\usr\bin\bash -lc 'curl -s -L -o develop.zip https://github.com/pyinstaller/pyinstaller/archive/develop.zip'
  - C:\msys64\usr\bin\bash -lc 'unzip -q develop.zip; cd pyinstaller-develop; /mingw64/bin/python3.exe setup.py --quiet install'
build_script:
  - C:\msys64\usr\bin\bash -lc 'cd /c/projects/audio; /mingw64/bin/python3.exe -m PyInstaller audio-run.py -cy -d bootloader -d imports -n audio-debug --log-level=TRACE --hidden-import=packaging.specifiers --hidden-import=packaging.requirements --exclude-module PyQt5.QtWebEngine --exclude-module PyQt5.QtWebEngineCore --exclude-module PyQt5.QtWebEngineWidgets --exclude-module PyQt5.QtQuickWidgets --exclude-module PyQt5.QtQuick --exclude-module PyQt5.QtQml --exclude-module PyQt5.QtWebChannel --exclude-module PyQt5.QtQtWebSockets --exclude-module PyQt5.QtWebKit --exclude-module lib2to3 --exclude-module tkinter'
artifacts:
  - path: dist
    type: zip
  - path: build
    type: zip
