install:
  - C:\msys64\usr\bin\bash -lc 'pacman -S --noconfirm unzip'
#  - C:\msys64\usr\bin\bash -lc 'pacman -S --noconfirm mingw-w64-x86_64-gst-python'
#  - C:\msys64\usr\bin\bash -lc 'pacman -S --noconfirm mingw-w64-x86_64-gst-plugins-good mingw-w64-x86_64-gst-plugins-bad'
  - C:\msys64\usr\bin\bash -lc 'pacman -S --noconfirm mingw-w64-x86_64-python3-pip'
  - C:\msys64\usr\bin\bash -lc '/mingw64/bin/python3.exe -c "import sys; print(sys.platform)"'
  - C:\msys64\usr\bin\bash -lc 'curl -L -o master.zip https://github.com/pypa/pip/archive/master.zip'
  - C:\msys64\usr\bin\bash -lc 'unzip master.zip; cd pip-master; /mingw64/bin/python3.exe setup.py install'
  - C:\msys64\usr\bin\bash -lc '/mingw64/bin/pip3.exe -v debug'
  - C:\msys64\usr\bin\bash -lc '/mingw64/bin/python3.exe -m pip -v -v -v install PyQt5'
  - C:\msys64\usr\bin\bash -lc '/mingw64/bin/python3.exe -m pip install PyQtChart'
  - C:\msys64\usr\bin\bash -lc '/mingw64/bin/python3.exe -m pip install numpy'
  - C:\msys64\usr\bin\bash -lc 'curl -L -o develop.zip https://github.com/springermac/pyinstaller/archive/_struct.zip'
  - C:\msys64\usr\bin\bash -lc 'unzip develop.zip; cd pyinstaller-_struct; /mingw64/bin/python3.exe setup.py install'
build_script:
  - C:\msys64\usr\bin\bash -lc 'cd /c/projects/audio; /mingw64/bin/python3.exe -m PyInstaller audio-run.py -cy -d bootloader -d imports -n audio-debug --log-level=TRACE --exclude-module PyQt5.QtWebEngine --exclude-module PyQt5.QtWebEngineCore --exclude-module PyQt5.QtWebEngineWidgets --exclude-module PyQt5.QtQuickWidgets --exclude-module PyQt5.QtQuick --exclude-module PyQt5.QtQml --exclude-module PyQt5.QtWebChannel --exclude-module PyQt5.QtQtWebSockets --exclude-module PyQt5.QtWebKit --exclude-module PyQt5.uic'
artifacts:
  - path: dist
    type: zip
  - path: build
    type: zip
