language: objective-c
install:
  - git clone https://github.com/MacPython/terryfy.git
  - source terryfy/travis_tools.sh
  - brew update
  - get_python_environment homebrew 3
  - brew install pyqt --with-python3
  - brew install gst-python
script:
  - python3.4 audio.py