matrix:
  include:
#    - os: osx
#      osx_image: xcode9.2
#      language: generic
#      cache:
#        directories:
#          - $HOME/Library/Caches/pip
#          - $HOME/Library/Caches/Homebrew
#      addons:
#        homebrew:
#          packages:
#            - python@3
#            - pygobject3
#            - gst-python
#            - gst-plugins-bad
#            - gst-plugins-ugly
#            - gst-plugins-good
#            - pyqt5
#          update: true
#      install:
#        - pip3 install --upgrade pip setuptools wheel
#        - pip3 install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
#      script:
#        - pyinstaller audio-debug.spec
    - os: windows
      language: sh
      cache:
        directories:
          - cache/msys2
      install:
        - powershell Start-Process -PassThru -Wait PowerShell -ArgumentList "'-Command Set-MpPreference -DisableArchiveScanning \$true'"
        - powershell Start-Process -PassThru -Wait PowerShell -ArgumentList "'-Command Set-MpPreference -DisableBehaviorMonitoring \$true'"
        - powershell Start-Process -PassThru -Wait PowerShell -ArgumentList "'-Command Set-MpPreference -DisableRealtimeMonitoring \$true'"
        - choco install -y --no-progress msys2 --package-parameters='"/NoUpdate"'
        - mv cache/msys2 /c/tools/msys64/var/cache/pacman/pkg
        - powershell "C:\tools\msys64\usr\bin\bash -lc 'pacman -Syu --noconfirm'"
        - powershell "C:\tools\msys64\usr\bin\bash -lc 'pacman -Su --noconfirm'"
        - powershell "C:\tools\msys64\usr\bin\bash -lc 'pacman -S --noconfirm mingw-w64-x86_64-gst-python'"
        - powershell "C:\tools\msys64\usr\bin\bash -lc 'pacman -S --noconfirm mingw-w64-x86_64-python3-pyqt5'"
        - powershell "C:\tools\msys64\usr\bin\bash -lc 'pacman -S --noconfirm mingw-w64-x86_64-python3-pip'"
        - powershell "C:\tools\msys64\usr\bin\bash -lc 'pacman -Ql --noconfirm mingw-w64-x86_64-python3-pip'"
        - powershell "C:\tools\msys64\usr\bin\bash -lc 'pip3.exe install https://github.com/pyinstaller/pyinstaller/archive/develop.zip'"
      script:
        - powershell "C:\tools\msys64\usr\bin\bash -lc 'python3.exe pyinstaller -h'"
      before_cache:
        - powershell "C:\tools\msys64\usr\bin\bash -lc 'pacman -Sc --noconfirm'"
        - mv /c/tools/msys64/var/cache/pacman/pkg cache/msys2

#after_success:
#  - zip -qr archive.zip dist/audio-debug.*
#addons:
#  artifacts:
#    paths:
#    - archive.zip
#deploy:
#  provider: script
#  script: ./deploy.sh
#  skip_cleanup: true
#  on:
#    branch: gst
#notifications:
#  slack:
#    secure: juocjqSjDTDkA7h6s18jCffGQMdU+JgAeDyl9LBB+02sFxn3HUpEF35JqJQ+SCZySv1htxPWyjOZYsJ8aU6kM+El1w/SfsUyiJoXK6eIM0CWamXmJZBjrGuZvPc4SAZrHhxCeB9NAy5Ogs17gNYT4mOM+wHtmY1nbHHAr/jMzi+cQinpaeqx//1Ct8ncv08DB0yX/uN7ByN8EK12J0B6oKM5nP2sVSFtZhlgBgJ+HWxnSzASRAxdidNu9Qhy5d6X9V54rRfYhpBwSycenFDoTUEzcYMOCO6Hsb3zkNPqfHeSAy99ITun0LwEsrm9t025I2N5t8B5Fb9aGVUucYmaSnD02WSORLPfpsIOr7cat8rWlHsOconQQocY/kxA7ki2nMJRa0ui5XM6xCsmqsLaGKorJDoyxuxWHcsLt7ARmA8E5JkT4HAsgzOQIL+F1mEoIsfDNejdATwUte550z7XzG2zt/lxR5HO1avxPGyj+G6EIfdoSood2i4X0aNFh+Q1Sdx5s1XBAumAW+AyzJwql33qSSgrth7SBk9sz2hvLJwC8rE2U+Tg3sw2NyfI0jwlSu5McU+KgqueBqZoirmNsGr7vezzk38UScLl8XLU0Dy7WoLEQfxfTh3fAIsjLau6ugJPf/A73x3opNh3z5xzoj3pTr9Wve5nJ4XrtBBVM0s=
