language: objective-c
install:
  - git clone https://github.com/MacPython/terryfy.git
  - source terryfy/travis_tools.sh
  - install_macports
  - sudo echo "macosx_deployment_target 10.8" >> /opt/local/etc/macports/macports.conf
  - sudo port -qs install py34-pyqt4
script:
  - python audio.py