language: objective-c
install:
  - git clone https://github.com/MacPython/terryfy.git
  - source terryfy/travis_tools.sh
  - install_macports
  - sudo port install py34-pyqt4 | cat
script:
  - python3.4 audio.py