# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/jonathanspringer/projects/audio/audio/resources/settingstab.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_settingsTab(object):
    def setupUi(self, settingsTab):
        settingsTab.setObjectName("settingsTab")
        settingsTab.resize(242, 182)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(settingsTab)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.monitorAudio = QtWidgets.QCheckBox(settingsTab)
        self.monitorAudio.setChecked(True)
        self.monitorAudio.setObjectName("monitorAudio")
        self.horizontalLayout_6.addWidget(self.monitorAudio)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_7.setSpacing(5)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.recordingSampleRate = QtWidgets.QComboBox(settingsTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.recordingSampleRate.sizePolicy().hasHeightForWidth())
        self.recordingSampleRate.setSizePolicy(sizePolicy)
        self.recordingSampleRate.setObjectName("recordingSampleRate")
        self.horizontalLayout_7.addWidget(self.recordingSampleRate)
        self.label_2 = QtWidgets.QLabel(settingsTab)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(settingsTab)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.recordingDirectory = QtWidgets.QLineEdit(settingsTab)
        self.recordingDirectory.setObjectName("recordingDirectory")
        self.horizontalLayout_3.addWidget(self.recordingDirectory)
        self.resetRecordingDirectory = QtWidgets.QPushButton(settingsTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resetRecordingDirectory.sizePolicy().hasHeightForWidth())
        self.resetRecordingDirectory.setSizePolicy(sizePolicy)
        self.resetRecordingDirectory.setMaximumSize(QtCore.QSize(20, 20))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.resetRecordingDirectory.setIcon(icon)
        self.resetRecordingDirectory.setIconSize(QtCore.QSize(16, 16))
        self.resetRecordingDirectory.setFlat(True)
        self.resetRecordingDirectory.setObjectName("resetRecordingDirectory")
        self.horizontalLayout_3.addWidget(self.resetRecordingDirectory)
        self.browseRecordingDirectory = QtWidgets.QPushButton(settingsTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browseRecordingDirectory.sizePolicy().hasHeightForWidth())
        self.browseRecordingDirectory.setSizePolicy(sizePolicy)
        self.browseRecordingDirectory.setMaximumSize(QtCore.QSize(20, 20))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/fileopen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.browseRecordingDirectory.setIcon(icon1)
        self.browseRecordingDirectory.setIconSize(QtCore.QSize(16, 16))
        self.browseRecordingDirectory.setFlat(True)
        self.browseRecordingDirectory.setObjectName("browseRecordingDirectory")
        self.horizontalLayout_3.addWidget(self.browseRecordingDirectory)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_8.setSpacing(5)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_3 = QtWidgets.QLabel(settingsTab)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_8.addWidget(self.label_3)
        self.recordingFilename = QtWidgets.QLineEdit(settingsTab)
        self.recordingFilename.setObjectName("recordingFilename")
        self.horizontalLayout_8.addWidget(self.recordingFilename)
        self.resetRecordingFilename = QtWidgets.QPushButton(settingsTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resetRecordingFilename.sizePolicy().hasHeightForWidth())
        self.resetRecordingFilename.setSizePolicy(sizePolicy)
        self.resetRecordingFilename.setMaximumSize(QtCore.QSize(20, 20))
        self.resetRecordingFilename.setText("")
        self.resetRecordingFilename.setIcon(icon)
        self.resetRecordingFilename.setIconSize(QtCore.QSize(16, 16))
        self.resetRecordingFilename.setFlat(True)
        self.resetRecordingFilename.setObjectName("resetRecordingFilename")
        self.horizontalLayout_8.addWidget(self.resetRecordingFilename)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.verticalLayout_3.addLayout(self.verticalLayout_4)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(12, 12, 12, 12)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.saveSettings = QtWidgets.QPushButton(settingsTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveSettings.sizePolicy().hasHeightForWidth())
        self.saveSettings.setSizePolicy(sizePolicy)
        self.saveSettings.setDefault(True)
        self.saveSettings.setObjectName("saveSettings")
        self.horizontalLayout.addWidget(self.saveSettings)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.label_2.setBuddy(self.recordingSampleRate)
        self.label.setBuddy(self.recordingDirectory)
        self.label_3.setBuddy(self.recordingFilename)

        self.retranslateUi(settingsTab)
        QtCore.QMetaObject.connectSlotsByName(settingsTab)

    def retranslateUi(self, settingsTab):
        _translate = QtCore.QCoreApplication.translate
        settingsTab.setWindowTitle(_translate("settingsTab", "Form"))
        self.monitorAudio.setToolTip(_translate("settingsTab", "<html><head/><body><p style=\"white-space:pre\"><span style=\" font-weight:600;\">Monitor audio even if the recording is paused or stopped</span></p></body></html>"))
        self.monitorAudio.setText(_translate("settingsTab", "Continuously Monitor Audio"))
        self.recordingSampleRate.setToolTip(_translate("settingsTab", "<html><head/><body><p style=\"white-space:pre\"><span style=\" font-weight:600;\">The sample rate the recorded file is saved at</span></p></body></html>"))
        self.label_2.setToolTip(_translate("settingsTab", "<html><head/><body><p style=\"white-space:pre\"><span style=\" font-weight:600;\">The sample rate the recorded file is saved at</span></p></body></html>"))
        self.label_2.setText(_translate("settingsTab", "Output Sample Rate"))
        self.label.setToolTip(_translate("settingsTab", "<html><head/><body><p style=\"white-space:pre\"><span style=\"font-weight:600;\">The directory the recorded file should be saved to</span></p></body></html>"))
        self.label.setText(_translate("settingsTab", "Recording Directory"))
        self.recordingDirectory.setToolTip(_translate("settingsTab", "<html><head/><body><p style=\"white-space:pre\"><span style=\"font-weight:600;\">The directory the recorded file should be saved to</span></p></body></html>"))
        self.resetRecordingDirectory.setToolTip(_translate("settingsTab", "<html><head/><body><p style=\"white-space:pre\"><span style=\"font-weight:600;\">Reset to the default directory</span></p><p style=\"white-space:pre\"><span style=\"font-style:italic;\">The default is the system music folder</span></p></body></html>"))
        self.browseRecordingDirectory.setToolTip(_translate("settingsTab", "<html><head/><body><p style=\"white-space:pre\"><span style=\"font-weight:600;\">Browse for the directory to save the recorded file</span></p></body></html>"))
        self.label_3.setToolTip(_translate("settingsTab", "<html><head/><body><p style=\"white-space:pre\"><span style=\"font-weight:600;\">The name the recording should be saved as</span></p><p style=\"white-space:pre\"><span style=\"font-style:italic;\">Can have variables in the name to insert the current date and/or time</span></p></body></html>"))
        self.label_3.setText(_translate("settingsTab", "Recording Filename"))
        self.recordingFilename.setToolTip(_translate("settingsTab", "<html><head/><body><p style=\"white-space:pre\"><span style=\"font-weight:600;\">The name the recording should be saved as</span></p><p style=\"white-space:pre\"><span style=\"font-style:italic;\">Can have variables in the name to insert the current date and/or time</span></p></body></html>"))
        self.resetRecordingFilename.setToolTip(_translate("settingsTab", "<html><head/><body><p style=\"white-space:pre\"><span style=\"font-weight:600;\">Reset to the default filename</span></p><p><span style=\"font-style:italic;\">The default is the current date</span></p></body></html>"))
        self.saveSettings.setToolTip(_translate("settingsTab", "<html><head/><body><p style=\"white-space:pre\"><span style=\" font-weight:600;\">Save the settings</span></p></body></html>"))
        self.saveSettings.setText(_translate("settingsTab", "Save"))

from . import resources_rc
